### ISSUE TITLE
Current Updated Prototype

### ISSUE THREAD

**Issue by ShardeHeim** [deco3500/UQExlpore#17]
This is our second stage prototype after user testing and refining previous mockups and design work. Using InVision, here is a link to a working demo. 
[https://invis.io/Y78LVJQME]

**Comment by ShardeHeim** [comment]
Updated Prototype

**Comment by rhysMckenzie** [comment]
Looking good, maybe with the first time pop-ups we could have a button somewhere that allows the user to view them again (especially with the game as they may forget how it works).
