### ISSUE TITLE
MockUp Update

### ISSUE THREAD

**Issue by ShardeHeim** [deco3500/UQExlpore#18]
Hi Team. <p>
Just giving you an update on the work I have been doing this week and over the break. Taking feedback we got from our user testing, Sofia and I have decided to go with the riddle and augmented reality feature as our reward option. I think UQ purple with a slight pink undertone can look really good. Tell me what you think of this? 
[https://drive.google.com/open?id=0B7FSO0zc14ThZms2c25wWkRKUTg]

<br>
@rhysMckenzie @shireeshshrivastava @sofiagrijalva

**Comment by sofiagrijalva** [comment]
Nice job Sharde , it looks so professional hahaha

**Comment by rhysMckenzie** [comment]
This looks like a legit app Sharde haha, awesome work

**Comment by simultech** [comment]
Just having a peek - looking great, well done!
