### ISSUE TITLE
Mock Ups of Feed and Customisable screens

### ISSUE THREAD

**Issue by rhysMckenzie** [deco3500/UQExlpore#19]
Working on creating mockups of the Feed screen and the screen/s that the user will see when they first sign up or decide to change/update their account settings

Feed Screen: [https://drive.google.com/open?id=0B-FSWFCEgaPXLURMclJoYVg5ZWs]

Preferences Screen: [https://drive.google.com/open?id=0B-FSWFCEgaPXZXVmTGdDemVRN28]

Profile Picture Screen: [https://drive.google.com/open?id=0B-FSWFCEgaPXbjVyS3ZLWmNvNW8]

Profile Details Screen: [https://drive.google.com/open?id=0B-FSWFCEgaPXX0tNVS1iWENRMzA]

Confirm Profile Screen: [https://drive.google.com/open?id=0B-FSWFCEgaPXLTFnNXdwZ01lNWc]

**Comment by ShardeHeim** [comment]
Awesome, I will use these and maybe tweak them a little to match the colour design scheme. I love the tag idea, we should definitely add that.
