### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by DK200** [deco3500/UQExlpore#2]
**Insightful**
It would be good that if every member in the UQ union to have access as it would be more convenient. Rather than giving someone the tasks to always updating he information on it.

**Appropriate**
It would be great for clubs and society members to be able to post on this application, as clubs and society would be able to invite more people to their events. 

**Actionable** 
It's really use as students of UQ would be aware of everything from various clubs and society. Which could act as a platform to promote these clubs and society.

**Comment by shireeshshrivastava** [comment]
Thank you for your review, these are the actual idea on which this platform based on which we decided to build a mobile application. Also we will also make sure that the requirements as mentioned will be incorporated into our project proposal.
