### ISSUE TITLE
Mock Ups of Eye Spy a Deal Tutorial

### ISSUE THREAD

**Issue by sofiagrijalva** [deco3500/UQExlpore#20]
Hello team !, mock ups are looking really nice, here is my part:
Sofia's Game Tutorial mock ups: [https://drive.google.com/open?id=0B-HOtvAkRuyHM3E1UDFvd2pwRDA]
i will like feedback on the number of pages, what about if we add more hints to make it easier to the user find the price.
Thanks guys :)

**Comment by ShardeHeim** [comment]
Awesome, I think if the user can't figure out the riddle they need to be able to either like you said, get hints or have access to a photo to help them. I think we should do a second round of user testing on the new design? @sofiagrijalva

**Comment by rhysMckenzie** [comment]
Looks awesome sofia, Ill try to base my mock ups off of this design to keep it coherent
