### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Ca5s1dy** [deco3500/UQExlpore#3]
Hi UQ explore,

Very interesting idea would defiantly benefit the UQ community because there are so many events that no one are actually aware of.

You said that normal students could request to host event but I think it would be cool if a student could make impromptu events. Like some people are having a social soccer game in front of Forgan Smith and want to invite anyone who has a break and is keen to come join in. This would great to allow groups of people who are keen to social to get involved in different activates and meet other people when ever they have spare time at Uni and don’t want to study.

**Comment by shireeshshrivastava** [comment]
Thanks for this new idea, we will try to accommodate this feature into our application.
