### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tshafiq** [deco3500/UQExlpore#4]
Hey Team UQExlpore,

Firstly, I like to state that the idea of your project is great. This app can help provide more information on what is going on around the UQ community. There are a lot of events that are happening around UQ and not everyone will know what event is happening. With the help of this app people will know what events are occurring where and when. I think it would be good if the normal students are able to post stuff on to the app rather than them having to request for permission.

Overall, the concept was good the idea was clear. Keep up with the good work.

**Comment by shireeshshrivastava** [comment]
Thank you for review comments. We will make sure to accommodate your idea into our application.
